/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MosqueService } from "../mosque.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MosqueCreateInput } from "./MosqueCreateInput";
import { Mosque } from "./Mosque";
import { MosqueFindManyArgs } from "./MosqueFindManyArgs";
import { MosqueWhereUniqueInput } from "./MosqueWhereUniqueInput";
import { MosqueUpdateInput } from "./MosqueUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MosqueControllerBase {
  constructor(
    protected readonly service: MosqueService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mosque })
  @nestAccessControl.UseRoles({
    resource: "Mosque",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMosque(@common.Body() data: MosqueCreateInput): Promise<Mosque> {
    return await this.service.createMosque({
      data: data,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        id: true,
        imamName: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Mosque] })
  @ApiNestedQuery(MosqueFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Mosque",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mosques(@common.Req() request: Request): Promise<Mosque[]> {
    const args = plainToClass(MosqueFindManyArgs, request.query);
    return this.service.mosques({
      ...args,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        id: true,
        imamName: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mosque })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Mosque",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mosque(
    @common.Param() params: MosqueWhereUniqueInput
  ): Promise<Mosque | null> {
    const result = await this.service.mosque({
      where: params,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        id: true,
        imamName: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mosque })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Mosque",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMosque(
    @common.Param() params: MosqueWhereUniqueInput,
    @common.Body() data: MosqueUpdateInput
  ): Promise<Mosque | null> {
    try {
      return await this.service.updateMosque({
        where: params,
        data: data,
        select: {
          address: true,
          contactNumber: true,
          createdAt: true,
          id: true,
          imamName: true,
          location: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mosque })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Mosque",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMosque(
    @common.Param() params: MosqueWhereUniqueInput
  ): Promise<Mosque | null> {
    try {
      return await this.service.deleteMosque({
        where: params,
        select: {
          address: true,
          contactNumber: true,
          createdAt: true,
          id: true,
          imamName: true,
          location: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
